=== cebula/dwmj/org.compass-project.compass/target/pax-eclipse/org/compass/core/compass-core-meta-data-2.2.dtd
<!-- Compass Meta Data DTD.

<!DOCTYPE compass-core-meta-data PUBLIC 
    "-//Compass/Compass Core Meta Data DTD 2.2//EN"
    "http://www.compass-project.org/dtd/compass-core-meta-data-2.2.dtd">
-->
<!ELEMENT compass-core-meta-data (
    meta-data-group* 
)>

<!ELEMENT meta-data-group (
    description?,
    uri?,
    alias*,
    meta-data* 
)>
    <!ATTLIST meta-data-group id CDATA #REQUIRED>
    <!ATTLIST meta-data-group displayName CDATA #IMPLIED>

<!ELEMENT alias (
    description?,
    uri?,
    name
)>
    <!ATTLIST alias id CDATA #REQUIRED>
    <!ATTLIST alias displayName CDATA #IMPLIED>

<!ELEMENT meta-data (
    description?,
    uri?,
    name,
    value*
)>
    <!ATTLIST meta-data id CDATA #REQUIRED>
    <!ATTLIST meta-data displayName CDATA #IMPLIED>

<!ELEMENT description (
    #PCDATA
)>

<!ELEMENT uri (
    #PCDATA
)>

<!ELEMENT name (
    #PCDATA
)>
    <!ATTLIST name format CDATA #IMPLIED>

<!ELEMENT value (
    #PCDATA
)>
    <!ATTLIST value id CDATA #REQUIRED>

=== cebula/dwmj/org.compass-project.compass/target/pax-eclipse/org/compass/vocabulary/dublin-core.cmd.xml
<!DOCTYPE compass-core-meta-data PUBLIC 
    "-//Compass/Compass Core Meta Data DTD 2.2//EN"
    "http://www.compass-project.org/dtd/compass-core-meta-data-2.2.dtd">

<compass-core-meta-data>

    <meta-data-group id="dublinCore" displayName="Dublin Core">

        <description>The Dublin Core Metadata Element Set</description>     
        <uri>http://dublincore.org/documents/2004/09/20/dcmi-terms/</uri>
    
        <meta-data id="contributor" displayName="Contributor">
            <description>An entity responsible for making contributions to the content of the resource</description>
            <uri>http://purl.org/dc/elements/1.1/contributor</uri>
            <name>contributor</name>
        </meta-data>

        <meta-data id="coverage" displayName="Coverage">
            <description>The extent or scope of the content of the resource</description>
            <uri>http://purl.org/dc/elements/1.1/coverage</uri>
            <name>coverage</name>
        </meta-data>

        <meta-data id="creator" displayName="Creator">
            <description>An entity primarily responsible for making the content of the resource</description>
            <uri>http://purl.org/dc/elements/1.1/creator</uri>
            <name>creator</name>
        </meta-data>
        
        <meta-data id="date" displayName="Date">
            <description>A date associated with an event in the life cycle of the resource</description>
            <uri>http://purl.org/dc/elements/1.1/date</uri>
            <name format="yyyy-MM-dd">date</name>
        </meta-data>
        
        <meta-data id="description" displayName="Description">
            <description>A date associated with an event in the life cycle of the resource</description>
            <uri>http://purl.org/dc/elements/1.1/description</uri>
            <name>description</name>
        </meta-data>
        
        <meta-data id="format" displayName="Format">
            <description>The physical or digital manifestation of the resource</description>
            <uri>http://purl.org/dc/elements/1.1/format</uri>
            <name>format</name>
        </meta-data>
        
        <meta-data id="identifier" displayName="Resource Identifier">
            <description>An unambiguous reference to the resource within a given context</description>
            <uri>http://purl.org/dc/elements/1.1/identifier</uri>
            <name>identifier</name>
        </meta-data>
        
        <meta-data id="language" displayName="Language">
            <description>A language of the intellectual content of the resource</description>
            <uri>http://purl.org/dc/elements/1.1/language</uri>
            <name>language</name>
        </meta-data>
        
        <meta-data id="publisher" displayName="Publisher">
            <description>An entity responsible for making the resource available</description>
            <uri>http://purl.org/dc/elements/1.1/publisher</uri>
            <name>publisher</name>
        </meta-data>
        
        <meta-data id="relation" displayName="Relation">
            <description>A reference to a related resource</description>
            <uri>http://purl.org/dc/elements/1.1/relation</uri>
            <name>relation</name>
        </meta-data>
        
        <meta-data id="rightsManagement" displayName="Rights Management">
            <description>Information about rights held in and over the resource</description>
            <uri>http://purl.org/dc/elements/1.1/rights</uri>
            <name>rightsManagement</name>
        </meta-data>
        
        <meta-data id="source" displayName="Source">
            <description>A reference to a resource from which the present resource is derived</description>
            <uri>http://purl.org/dc/elements/1.1/source</uri>
            <name>source</name>
        </meta-data>
        
        <meta-data id="subject" displayName="Subject and Keywords">
            <description>The topic of the content of the resource</description>
            <uri>http://purl.org/dc/elements/1.1/subject</uri>
            <name>subject</name>
        </meta-data>
        
        <meta-data id="title" displayName="Title">
            <description>A name given to the resource</description>
            <uri>http://purl.org/dc/elements/1.1/title</uri>
            <name>title</name>
        </meta-data>

        <meta-data id="resourceType" displayName="Resource Type">
            <description>The nature or genre of the content of the resource</description>
            <uri>http://purl.org/dc/elements/1.1/type</uri>
            <name>resourceType</name>
        </meta-data>

    </meta-data-group>

    <meta-data-group id="dublinCoreOthers" displayName="Dublin Core Others">
    
        <description>Dublin Core Other Elements and Element Refinements</description>       
        <uri>http://dublincore.org/documents/2004/09/20/dcmi-terms/</uri>
        
        <meta-data id="abstract" displayName="Abstract">
            <description>A summary of the content of the resource</description>
            <uri>http://purl.org/dc/terms/abstract</uri>
            <name>abstract</name>
        </meta-data>

        <meta-data id="accessRights" displayName="Access Rights">
            <description>Information about who can access the resource or an indication of its security status</description>
            <uri>http://purl.org/dc/terms/accessRights</uri>
            <name>accessRights</name>
        </meta-data>

        <meta-data id="alternative" displayName="Alternative">
            <description>Any form of the title used as a substitute or alternative to the formal title of the resource</description>
            <uri>http://purl.org/dc/terms/alternative</uri>
            <name>alternative</name>
        </meta-data>

        <meta-data id="audience" displayName="Audience">
            <description>A class of entity for whom the resource is intended or useful</description>
            <uri>http://purl.org/dc/terms/audience</uri>
            <name>audience</name>
        </meta-data>

        <meta-data id="available" displayName="Available">
            <description>Date (often a range) that the resource will become or did become available</description>
            <uri>http://purl.org/dc/terms/available</uri>
            <name>available</name>
        </meta-data>
        
        <meta-data id="bibliographicCitation" displayName="Bibliographic Citation">
            <description>A bibliographic reference for the resource</description>
            <uri>http://purl.org/dc/terms/bibliographicCitation</uri>
            <name>bibliographicCitation</name>
        </meta-data>
        
        <meta-data id="conformsTo" displayName="Conforms To">
            <description>A reference to an established standard to which the resource conforms</description>
            <uri>http://purl.org/dc/terms/conformsTo</uri>
            <name>conformsTo</name>
        </meta-data>
        
        <meta-data id="created" displayName="Created">
            <description>Date of creation of the resource</description>
            <uri>http://purl.org/dc/terms/created</uri>
            <name>created</name>
        </meta-data>

        <meta-data id="dateAccepted" displayName="Date Accepted">
            <description>Date of acceptance of the resource (e.g. of thesis by university department, of article by journal, etc.)</description>
            <uri>http://purl.org/dc/terms/dateAccepted</uri>
            <name>dateAccepted</name>
        </meta-data>
        
        <meta-data id="dateCopyrighted" displayName="Date Copyrighted">
            <description>Date of a statement of copyright</description>
            <uri>http://purl.org/dc/terms/dateCopyrighted</uri>
            <name>dateCopyrighted</name>
        </meta-data>
        
        <meta-data id="dateSubmitted" displayName="Date Submitted">
            <description>Date of submission of the resource (e.g. thesis, articles, etc.)</description>
            <uri>http://purl.org/dc/terms/dateSubmitted</uri>
            <name>dateSubmitted</name>
        </meta-data>
        
        <meta-data id="audienceEducationLevel" displayName="Audience Education Level">
            <description>A general statement describing the education or training context. Alternatively, a more specific statement of the location of the audience in terms of its progression through an education or training context</description>
            <uri>http://purl.org/dc/terms/educationLevel</uri>
            <name>audienceEducationLevel</name>
        </meta-data>
        
        <meta-data id="extent" displayName="Extent">
            <description>The size or duration of the resource</description>
            <uri>http://purl.org/dc/terms/extent</uri>
            <name>extent</name>
        </meta-data>
        
        <meta-data id="hasFormat" displayName="Has Format">
            <description>The described resource pre-existed the referenced resource, which is essentially the same intellectual content presented in another format</description>
            <uri>http://purl.org/dc/terms/hasFormat</uri>
            <name>hasFormat</name>
        </meta-data>
        
        <meta-data id="hasPart" displayName="Has Part">
            <description>The described resource includes the referenced resource either physically or logically</description>
            <uri>http://purl.org/dc/terms/hasPart</uri>
            <name>hasPart</name>
        </meta-data>
        
        <meta-data id="hasVersion" displayName="Has Version">
            <description>The described resource has a version, edition, or adaptation, namely, the referenced resource</description>
            <uri>http://purl.org/dc/terms/hasVersion</uri>
            <name>hasVersion</name>
        </meta-data>
        
        <meta-data id="isFormatOf" displayName="Is Format Of">
